$ANSIBLE_VAULT;1.2;AES256;homelab
39306138636362316633633539336139636665356238633062366136633739363964396631313362
3133336664623935316236396339616138626165313665330a333965366438633362303263353963
33653634353630613434623137376463323563643362386336323238643462333163356137346334
3034383731653437620a633934643135323561323135633463373239613866623838636166343334
61666665626162313234366636643263333335343730656363326537373164396265653036333236
39616261306235353063306265363662663134376363333034353639633562383466363365363962
37336563373763356630353139353534663632646264643361336135643831313561303336613963
35323230333762316436623738326632356333376535633566623632356366313534316631383632
39393932616564313364323434343530623863306530386165376139383361333566316464356433
38306639363532663664653665616336653132333962623364663936373739393538356363366536
39316130366235643332633236666666653033613234656262626462343066303637643630643766
61323234353065323733303166646563393636356364363734623433306630646332376135316662
61613866383337376634353235383332373734346335616663383936613730646562376432336266
61303131303363656532353639643736613932633562646465366633333738303462643534373965
35323365656166313036643336363835613136656339336133326463303537376134356339656266
32623930353035623865316333323265636263613130643131626465613037626236633539336137
36636536623266383862643133316132616430303134633331313733363332383861386433643161
61303361326135646536353339646235336231343563616330626139613234633735396339323532
62646632633238303738383035313432313830613038333730373865646361626431323833343630
39336230323938636461346532623435313930373738616133363832336633333064613161383032
66366330373662623763323832616430366166623933376564303562393462323830336133323134
62663839383137656434386531363732313465666137656631616264656562373163383864613765
30646131356237356539373930643731623330623836313761396231653132623935316265613037
37393135316336363166626565303139623961376535666531383032323066323534626561653533
61643762336666333637353565393737316163646464373439336533623662643035663466383737
37313037353838363834383738333633663531643531383136633434306365376563626166613165
36366162666663623831376239356164653731316333376261633238663732353833363233326464
65366539363438303164663864323930636537363832343033363833346137666365616563326534
34376561666134313364313566363532343131383434636539336438643238326131353536376430
35363763653139616661323364613831393964643962303133616230313231633631376364616464
36643231336663666234663839363632636430353262303930393866636566656464333632636230
36613937636337363363373163353263333237373536363034643638653366633231623662363230
63626339336434633866376564633039356634633734643661653237356631306138306534343330
39353931373864643065366665663862383662616438346664356261383761313933363664326166
30386665663331353337383563666234366462326364376239343639353631323364326330633263
37663566383135346335663935336330313035306433376262646636613032346661393861626537
34613432663466303264656632643136363361643731333536363234376530303730626463393665
38343933313664663835333061656361643165343032396333363063333765386339666466643632
62356436666264663366333635303930323462643562393931636461313632396363393334623635
64363039623330336539363463356462613765663965393562353531326338376466376335373261
37653138386334636136626132646361313366636433663365363632303733653433613833366633
33336632356138326134666535306163643830306333393264303937393630366162326666633036
30646133656137336233343037616534313261306239383934663236613861313235653937333863
63666635613235356338323433333231613261316664633665353930616364333763396664326166
39383765616665383966333932623232643533643939356339343161383738633536303963353066
65373061313330393362396639306633353035643934633435326263633462306162316130646262
63343434363835626631376661316436656161636633653932353465326438666337626337623837
36363161353965343566616238616232653133373166326632393632656135626239333764376266
32653730346631333931656265613638353865393863663561636537353333623366376432613033
34383162313538386433663064386131383133616338653336313333666439633066316464323733
32623035623161326363343866353932383361623163663435343736356634636163636636633434
37626232333934626132633537333034366162313132303134373633666237323561623635336336
63626337383362623137326235313632346463336262346432396566653235646366656238663761
32613136303732663433306438343362373833363164663132313039386332646161343335353630
64633737646432656465616639313237396435343939316637616131396337363863613762343738
34643466316463356139303032646638396434633635303939653038393339643137356636626332
37363139323262346535363366303035343433376265663066316464326163386136383032383337
66386236366231393830363066616662386231333333303439323839373737616530346536303062
32643365636565326234623963666235343632353234303261383530323730346338646531613264
65396162343730666139643038316164663032356665656131666438666432613966303239363333
65363166636665376234636564353930333863653866643565393135396532393434336536353933
36613034343032333762656335306461626134343434343766613133356466333561663561313638
37636535353331646365626162636335356138373662656334613066366638643261633637346131
63653133626635613038313436333664623463313831633531646635386531663935626231613966
35646138643430633437636232643862383235653465343832376138363939313335663466343134
39653463646338623636633838656132653431386133393736326338656137326561306533663037
63313432326630663463656635663032306336313663616661356362663032656431616164323234
61366236373463303130663037613234346632643165343331376363666365333532373337303562
61333037333731396135383936393133306331613539643133663263323465333166366562623232
62346238326461326636663736613363373736343065336330366366366463366463363436613963
65393937373433663361373562646464343136386566626137383938333638353366633436636436
66313361373236346338626165646366393562646134346166326566376263373763613461353361
64336164376634626665393830326364663135373838323335613162373438616237636337656464
36353262663233373137363438316134376164666662393838343661643736366534376539316462
38383737343732623862343265613539336266343539646630343834626164366331333662373835
33396339383830373938633237623038323266323563636632316661303437646236326532643031
62353437626537336466386430303530373530323465626265343334383166623434643836656631
38336433646537663131383635346436666438623361623630663337306136396563663464343030
66623464363462643964386534613237323538346661323732363735636266636532346435646338
36633933656637373738343065333431303132326463393430346165393337366662356138643932
30393435383839626562663138323161346133393931303166303338383862633739303532313736
31653664666364633833303833616664323963303435383466616364396366653962363763376337
39623062313634313134633939653463646530646336376238393732396365613062393930373861
36383530306239653661326633623865633066653365663036323861383537353366313464666565
39336366306466316430633030663663313835346463303739316438333234643639393331383830
30646530623566643566313465616662306238333233633131653866663735643837393836343661
31626432346233663864363539616431313437636562306432323433343139393236383364616132
64663134663563386233663733303033333435393132653937633530616335636236353839346533
36346664303264343233656437393066346165313832366361343439666366363433353736633530
66303964353966336130313730393862373036316465636466343337393835336230623833333565
33356139616165323534303039653030396636623563623733386437363363623165363430653632
39363264396230393836353335313361303264306663383635653736336433303262333461633630
64656331333864346336613739363462613834383339646465393939326261656532346435393366
65666237363630393638366533613638623136303930376232623863646437633930333732393762
35666564633537616163616536623661326564646463656563653231646233383864366638346235
63643536363264613939383064336330646631656564343664653866383030373034353263386562
36366235366666336339663633383639636464373938663739386530663038323433616161353839
34373831326331643934376364373839316161623632306266306133376137656662393061613931
38616332383161613466613532363135396665333830646462366634393734616531636666636561
31653332336333336234653463646432346139393564366232336435663562643035396434386261
61343731373563316166326436376266393535633634646462363761326534303831333364393731
66656262656338616431623237333937363937303733373165643234636362366164313437313866
34623864383863336234653832666262363434396433386435363862633431376232346139666537
34366262643563626235313162353266363631663339643963313364656530383134666136663130
66396538633462346238323263366331326237333131323365353036613531336139393538613037
31336563663461383335313861333633346266383332633263366364336330393839356235653134
36643364343639623936373334613334313264363061623066626133323866366463363461633533
62663539636433353839396139303265336566613332363934346533653336636161646435306335
62393736656432383837636138613339396131303936616335613932393965366661313061313664
38323365613365656133393664646534323538656461383464363961316138643861326136623135
33623365646532653161626561323331663331333862373134376638616237323966396166306331
34633864386434343837323534636361383539373135643938656631373864396332393334363066
61376437623565386266313934303162343163356566393335613135306332363932363566313136
61626566323363393331613362376364373264623664356161336639643431643833393336613865
39346663363465636139623634343765626161646433343865653165363636366231306366666564
64643362643061643535613633326633306563313137346532346137616438333463353338336166
61613636646461616264386438353836373661313030303234376563336235636535366438636665
61633430366161326265663738626330333238613537343564383266666230316432313432653763
66303430343333653130623033333336313438393531303932346163393061643134303333383436
61643239383664633761636439356433376464353364373335343437353964663262356565373661
63613165396335623466306535303165306163373663666638303931663861333664373265646636
61336533653633376338616561313731326365376137613739316335623538623934343337626530
30613632616663396530666334616439343038633564356462366364333232613263356336383236
63643861306432353139366266663737353862316535356365333635643935383136386463306331
61363864323130636333343865376231613632613266643537313837646333383738623736646636
65333662646430666163643732333234653334366437373231346662306133366266366630663032
64326664336665363364373733623662323831663839303463613634636666323336633334613966
33663537386364366562343631303430326335633438623561363431316231346361636562393936
63646539653534666638646565356465373930343635633364376365383662306238623366613139
33303665666338613830303261343938343265643166613462396533636634636135303533636336
33303635353236646663323036653536386265383639393631666561386361363638306661393037
63333063646339633635336532333337393431396232366236663466666165643331666530666166
30383262666239623234373139353861636535303534393333633764363330613433636266326431
63313364363435333864353164353164303333366662363831333834363264346564306538643563
66356363303132653534373435636536376237376431613830316539343662643136633166623537
37376232633166306263313839366665663963303033326133396331353166323833623037313635
36356630653333623238666437623037313837386438303337633931393137303363383436356330
36313561636430386130333730633533346134633538653962616564656463306563303962643335
30303234353665396631393761653037663739616638623663333535636233323036353630363932
33616531613130623835633763333639306162303032623538633539616639643739613563646237
36323063613465663265613230633339653664333061343261633533303638333030353366373332
37616433356263623966363062633636656336303738373563656234323032653766353033396135
35356165636237663064313066326262643434366231636263316530363436343064343336386331
34313536386232343232386562373335396365343935363831336537353438653333333764613930
62336163326566323361303835653863396138323932643730313566616231393063643630666430
31326664343232303134666131333863303664643836626130646266653635623262643465656638
63386163613537663962613235393866643063343766303933363636383631316430643666316434
39646536616239663837653061323662643231616538356139343330383138363566396637646135
37633033366531653136346362636237656430373662316463633062613563323633393930356162
39656134363563656662613630343062333335376562633532623031633266303435653439383361
31326437396130363766613865336166336462316263386664656335336466306435376239373061
62346331363166363430633765313332663831346339366138616665356630366631616663346135
39356165646130346139306366393831326361613065643431623136373732356533363833353936
62366530656631326665393033333962663235373562666634303734626635336163336131316133
62663865623961613533303661613465373236656533613136636663623335666237336537303063
30646532613130313736303937663765383866346337656634396163623838336363663735613539
66333236316665336233313834353533636266353261616432343034616433623763633632646266
30666432663964383338613535303861616535363239393039303930323935343331336537616432
35393736346137653164626465636466343262363832646663333232306462303237386561376331
36366266653035653062646233653533633630343130343730656331363564313264636532396566
30376130306463386262393165356264653865373237393337653530323666633165
