galaxy_info:
  author: Filipe Utzig <filipe@gringolito.com>
  description: Set-up Unbound as a recursive DNS server with private authoritative zone delegation
  namespace: gringolito
  role_name: unbound
  license: Beerware
  min_ansible_version: "2.14"

  galaxy_tags:
    - unbound
    - dns

dependencies: []
