galaxy_info:
  author: Filipe Utzig <filipe@gringolito.com>
  description: Deploys a Pi-Hole Podman Container as a SystemD service
  namespace: gringolito
  role_name: pihole
  license: Beerware
  min_ansible_version: "2.14"

  galaxy_tags:
    - pihole
    - podman
    - systemd
    - dns
    - dhcp

dependencies: []
