---
- name: Restart PowerDNS
  ansible.builtin.systemd_service:
    name: pdns
    state: restarted
  become: true

- name: Check PowerDNS zones
  ansible.builtin.command: pdnsutil zone check-all
  changed_when: false
  check_mode: false
