galaxy_info:
  author: Filipe Utzig <filipe@gringolito.com>
  description: Set-up ISC Kea DHCPv4 and DHCP-DDNS servers
  namespace: gringolito
  role_name: isc_kea
  license: Beerware
  min_ansible_version: "2.15"

  galaxy_tags:
    - kea
    - isc
    - dhcp
    - dhcpv4
    - ipv4
    - ddns

dependencies: []
