---
isc_kea_apt_repository_url: https://dl.cloudsmith.io/public/isc/kea-3-0/deb/{{ ansible_distribution | lower }}
isc_kea_apt_repository_key: https://dl.cloudsmith.io/public/isc/kea-3-0/gpg.B16C44CD45514C3C.key
