---
- name: Install Unbound
  ansible.builtin.apt:
    name: unbound
    state: present
  become: true
  tags:
    - unbound

- name: Enable Unbound service to automatically start on each boot
  ansible.builtin.systemd_service:
    name: unbound
    state: started
    enabled: true
  become: true
  tags:
    - unbound

- name: Set-up Unbound as a recursive DNS resolver
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/resolver.conf
    backup: true
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/unbound-checkconf %s
  become: true
  notify:
    - Restart Unbound
  tags:
    - unbound
