---
roles:
  - name: geerlingguy.repo-epel
    version: 3.1.1
  - name: geerlingguy.containerd
    version: 1.3.1
  - name: geerlingguy.kubernetes
    version: 8.0.0
  - name: geerlingguy.helm
    version: 1.0.1

collections:
  - name: cloud.terraform
    version: 4.0.0
  - name: community.general
    version: 12.0.1
  - name: kubernetes.core
    version: 6.2.0
  - name: community.zabbix
    version: 4.1.1
